[workspace]
resolver = "2"
members = ["les_bin", "les_nes"]
default-members = ["les_bin"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
opt-level = 2
codegen-units = 1
