[package]
name = "les_bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
les_nes = { path = "../les_nes" }
bevy = { version = "0.8.0", default-features = false, features = [
    "bevy_gilrs",
    "bevy_winit",
    "bevy_render",
    "bevy_core_pipeline",
] }
bevy_egui = "0.15.0"
rfd = "0.8.2"
crossbeam-channel = "0.5.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cpal = "0.13.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
cpal = { version = "0.13.5", features = ["wasm-bindgen"] }
console_error_panic_hook = "0.1.7"
